name: TitanicApp
description: App to Learn Logistic Regression
status: active
dev_path: apps
role: project
tags:
  - apps
  - react
language: js
setup:
  - yarn dev
env: []
services: []
depends_on: []
workspace: []
update_strategy: []
priority: []